SHTL-278 Como un administrador necesito ver la marca de mi hotel en el dashboard así podré sentir pertenencia de mi marca
Contler/monorepo-web pull request #129
Opened 2021-02-09 13:02 UTC by JoanSerna

feat(view) add template defined on hotel data for app Hotel

Loom: 
https://www.loom.com/share/ce12add31b6f4b06ad1fbe5f178fcf50

2021-02-09 14:55 UTC, ruedagato reviewed
check comments

2021-02-09 14:55 UTC, ruedagato commented on apps/hotel/src/directives/btn-hotel.directive.ts
> +          this.formValidationSubscription$.add(
if you are validating `formValidationSubscription$` exist why are you create again the subscribe?

2021-02-09 14:55 UTC, ruedagato commented on apps/hotel/src/directives/btn-hotel.directive.ts
> +  @Input() formValidation: FormGroup = null;
```suggestion
  @Input() disabled: booleanl;
```
maybe if you catch the disable property your logic would be easier

2021-02-09 14:55 UTC, ruedagato commented on apps/hotel/src/directives/color-slide-toggle.directive.ts
> +    /**
remove comment

2021-02-09 14:55 UTC, ruedagato commented on apps/hotel/src/guest/components/model-new-guest/model-new-guest.component.html
> +    *ngIf="guestGroup.invalid"
is necessary two buttons ?

2021-02-09 14:55 UTC, ruedagato commented on apps/hotel/src/home/page/admin-home/admin-home.component.ts
> +    this.authService.$employer.subscribe((user) => {
I see this code doesn't have any purpose, remove it

2021-02-09 14:55 UTC, ruedagato commented on apps/hotel/src/statistics/statistics.component.scss
> +    stroke: red;
why do you set this color?

2021-02-09 15:02 UTC, JoanSerna commented on apps/hotel/src/directives/btn-hotel.directive.ts
> +          this.formValidationSubscription$.add(
Because if it does not exist and it is null, I do not have the `.add` property, but if instead before in the constructor it had a statement at this point: onChanges if I can use the `.add`

But it is true receiving a property disable it is easier the logic

2021-02-09 15:34 UTC, JoanSerna commented
> check comments


- [x] Change `BtnHotelDirective` with disabled property 
- [x] Remove block comment 
- [x] code unused

2021-02-09 15:45 UTC, ruedagato requested changes

2021-02-09 15:45 UTC, ruedagato commented on apps/hotel/src/directives/btn-hotel.directive.ts
> +  /**
this doc now is not necessary

2021-02-09 15:45 UTC, ruedagato commented on apps/hotel/src/home/page/admin-home/admin-home.component.ts
> +import { HotelService } from '@contler/core';
remove if it doesn't use

2021-02-09 15:45 UTC, ruedagato commented on apps/hotel/src/home/page/admin-home/admin-home.component.ts
> +import { AuthService } from 'hotel/services/auth.service';
remove if it doesn't use

2021-02-09 15:45 UTC, ruedagato commented on apps/hotel/src/home/page/admin-home/admin-home.component.ts
> +    private authService: AuthService,
remove if it doesn't use

2021-02-09 16:13 UTC, ruedagato commented on apps/hotel/src/directives/btn-hotel.directive.ts
> +    if (this.formValidationSubscription$) {
it is not necessary

2021-02-09 16:13 UTC, ruedagato commented on apps/hotel/src/directives/btn-hotel.directive.ts
> +  private formValidationSubscription$: Subscription;
it is not necessary

2021-02-09 22:20 UTC, JoanSerna commented on apps/hotel/src/directives/btn-hotel.directive.ts
> +  private formValidationSubscription$: Subscription;
fixed :heavy_check_mark:

2021-02-11 14:54 UTC, ruedagato approved these changes

2021-02-11 14:54 UTC, merged