[SHTL-156] Create CRUD to restaurant component
Contler/monorepo-web pull request #13
Opened 2020-09-07 23:27 UTC by andrewT89

[SHTL-156](https://pappcorn.atlassian.net/browse/SHTL-156)
## front > Como un administrador necesito crear/editar/eliminar restaurantes para especificar sus menús así podré darle al usuario la carta según restaurante

Creación de componente
# evidencia
![image](https://user-images.githubusercontent.com/20249366/92420218-bdead300-f137-11ea-9e23-97012c52b0b0.png)

2020-09-07 23:55 UTC, ruedagato requested changes

2020-09-07 23:55 UTC, ruedagato commented on apps/hotel/src/restaurant/page/restaurant/restaurant.component.ts
> +        // this.restaurants = this.restaurants.filter(
remove comments line

2020-09-07 23:55 UTC, ruedagato commented on apps/hotel/src/restaurant/page/restaurant/restaurant.component.ts
> +  public restaurantGroup: FormGroup;
not is necessary public word on public variables

2020-09-07 23:55 UTC, ruedagato commented on apps/hotel/src/restaurant/page/restaurant/restaurant.component.ts
> +  public save() {
not is nessesary public word on public methods

2020-09-07 23:55 UTC, ruedagato commented on apps/hotel/src/restaurant/services/restaurant.service.ts
> +export class RestaurantService {
all these services are already created on https://github.com/Contler/monorepo-web/blob/master/libs/core/src/lib/services/restaurant/restaurant.service.ts#L14 please remove this service and use the already created

2020-09-07 23:55 UTC, ruedagato commented on apps/hotel/src/restaurant/editable/edit-mode.directive.ts
> +export class EditModeDirective {
why do you create this directive?

2020-09-08 00:18 UTC, andrewT89 commented on apps/hotel/src/restaurant/editable/edit-mode.directive.ts
> +export class EditModeDirective {
This directive is created for editing the fields in the restaurant list.

2020-09-08 00:22 UTC, andrewT89 commented on apps/hotel/src/restaurant/services/restaurant.service.ts
> +export class RestaurantService {
This service was not created by me and it affects the backend changes.

2020-09-08 01:21 UTC, ruedagato requested changes

2020-09-08 01:21 UTC, ruedagato commented on apps/hotel/src/restaurant/page/restaurant/restaurant.component.ts
> +    const a = this.restaurantArray.at(index).get(fieldName) as FormControl;
this const never is used

2020-09-08 01:21 UTC, ruedagato commented on apps/hotel/src/restaurant/editable/edit-on-enter.directive.ts
> +  selector: '[contlerEeditableOnEnter]',
this directive never is used

2020-09-08 01:21 UTC, ruedagato commented on apps/hotel/src/restaurant/editable/editable.component.ts
> +  ngOnDestroy() {}
remove method if no produce any effect

2020-09-08 01:21 UTC, ruedagato commented on apps/hotel/src/restaurant/page/restaurant/restaurant.component.html
> +                        Campo requerido <strong>required</strong>
confirm correct message when the error is present, the communication for the user should be only in one language. confirm the text and the style with ricardo mejia

2020-09-08 01:21 UTC, ruedagato commented on apps/hotel/src/restaurant/page/restaurant/restaurant.component.scss
> +    button {
use a class, never create stiles directly for an element unless it was for globals styles. it could generate problems with new changes or new develops

2020-09-08 01:21 UTC, ruedagato commented on apps/hotel/src/restaurant/page/restaurant/restaurant.component.ts
> +import { RestaurantService } from '../../../../../../libs/core/src/lib/services/restaurant/restaurant.service';
```suggestion
import { RestaurantService } from '@contler/ui';
```

2020-09-09 20:38 UTC, ruedagato approved these changes

2020-09-09 20:41 UTC, merged

2020-09-09 20:42 UTC, andrewT89 commented
merge y finalización de historia.