[SHTL-229] Huésped - Si estoy logueado como un huésped, y se pasa mi fecha de salida, igual puedo seguir pidiendo cosas.
Contler/monorepo-web pull request #84
Opened 2020-10-20 15:01 UTC by andrewT89

[SHTL-229](https://pappcorn.atlassian.net/browse/SHTL-229)

- Ajuste para verificar si el huésped tiene la fecha de salida vigente cuando se recarga la pagina
- Agregar método que valide si el usuario tiene la fecha de salida vigente al recargar la pantalla.

# Evidencias:

Fecha de salida:
![image](https://user-images.githubusercontent.com/20249366/96604005-38bc1780-12ba-11eb-9484-be32b86574c6.png)

Ingreso huésped con fecha de salida vigente:

![SHTL-229-Guest-ingreso](https://user-images.githubusercontent.com/20249366/96604254-82a4fd80-12ba-11eb-88d1-72985216b868.gif)

Cambio de fecha de salida:

![image](https://user-images.githubusercontent.com/20249366/96604425-b849e680-12ba-11eb-9a4f-aba4a443d4a8.png)

Recargar pagina para validación de fecha de saluda del usuario:

![SHTL-229-Guest-recarga-pag](https://user-images.githubusercontent.com/20249366/96604841-2c848a00-12bb-11eb-99a5-3062a6e2248a.gif)

2020-10-20 19:34 UTC, ruedagato requested changes

2020-10-20 19:34 UTC, ruedagato commented on apps/guest/src/app/app.component.ts
> +  constructor() {}
remove constructor if it is empty

2020-10-20 19:34 UTC, ruedagato commented on apps/guest/src/common-components/guards/avalible-user.guard.ts
> +        tap((guest) => guest),
why do you need this tap?

2020-10-20 19:34 UTC, ruedagato commented on apps/guest/src/common-components/guards/avalible-user.guard.ts
> +    this.afAuth.user
you must return the observable

2020-10-20 19:34 UTC, ruedagato commented on apps/guest/src/common-components/guards/avalible-user.guard.ts
> +    return true;
you always are returning true

2020-10-20 19:43 UTC, andrewT89 commented on apps/guest/src/common-components/guards/avalible-user.guard.ts
> +        tap((guest) => guest),
I already checked and it is not necessary. I already delete it

2020-10-21 00:13 UTC, ruedagato approved these changes

2020-10-21 01:04 UTC, merged